lab_1/urls.py
from django.urls import path, include
from .views import index, friend_list

urlpatterns = [
    path('', index, name='index'),
    path('friends', friend_list, name='friends'),
]

lab_2/urls.py
from django.urls import path, include
from .views import index, xml, json

urlpatterns = [
    path('', index, name='index'),
    path('json', json, name='json'),
    path('xml', xml, name='xml'),
]

lab_3/urls.py
from django.urls import path, include
from .views import index, add_friend

urlpatterns = [
    path('', index, name='index'),
    path('add', add_friend, name='add_friend'),
]

lab_4/urls.py
from django.urls import path, include
from .views import index, add_note, note_list

urlpatterns = [
    path('', index, name='index'),
    path('add-note', add_note, name='add_note'),
    path('note-list', note_list, name='note_list'),
]

lab_5/urls.py
from django.urls import path, include
from .views import index, add_note, note_list, EditNote, DeleteNote

urlpatterns = [
    path('', index, name='index'),
    path('add-note', add_note, name='add_note'),
    path('note-list', note_list, name='note_list'),
    path('edit-note',  EditNote.as_view(), name='edit_note'),
    path('delete-note',  DeleteNote.as_view(), name='delete_note'),


]

praktikum/urls.py
from django.urls import path, include, re_path
from django.contrib import admin
import lab_1.urls, lab_2.urls, lab_3.urls, lab_4.urls
from lab_1.views import index as index_lab1

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lab-1/', include(lab_1.urls)),
    path('lab-2/', include(lab_2.urls)),
    path('lab-3/', include(lab_3.urls)),
    path('lab-4/', include(lab_4.urls)),
    re_path(r'^$', index_lab1, name='index'),
]

lab_1/models.py
from django.db import models

class Friend(models.Model):
    name = models.CharField(max_length=30)
    npm = models.CharField(max_length=10)
    DOB = models.DateField()

lab_2/models.py
from django.db import models

class Note(models.Model):
    note_to = models.CharField(max_length=30)
    note_from = models.CharField(max_length=30)
    title = models.CharField(max_length=30)
    message = models.TextField()
    

lab_3/models.py
from django.db import models

# Create your models here.

lab_4/models.py
from django.db import models

# Create your models here.

lab_5/models.py
from django.db import models

# Create your models here.

lab_3/forms.py
from django import forms
from lab_1.models import Friend

class FriendForm(forms.ModelForm):
    class Meta:
        model = Friend
        fields = "__all__"
        labels = {"name":"Full Name", 
                "npm":"NPM", 
                "DOB":"Date of Birth"
                }

lab_4/forms.py
from django import forms
from lab_2.models import Note

class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = "__all__"

lab_5/forms.py
from django import forms
from lab_2.models import Note

class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = "__all__"

lab_1/views.py
from django.shortcuts import render
from datetime import datetime, date
from .models import Friend

mhs_name = 'Muhammad Fikri Haryanto'
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(2001, 12, 19)
npm = '2006525053'


def index(request):
    response = {'name': mhs_name,
                'age': calculate_age(birth_date.year),
                'npm': npm}
    return render(request, 'index_lab1.html', response)


def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0


def friend_list(request):
    friend_list = Friend.objects.all()
    response = {'friend_list': friend_list}
    return render(request, 'friend_list_lab1.html', response)

lab_2/views.py
from django.shortcuts import render
from django.http.response import HttpResponse
from django.core import serializers
from .models import Note

def index(request):
    note_list = Note.objects.all()
    response = {'note_list': note_list,
            }
    return render(request, 'lab2.html', response)

def xml(request):
    data = serializers.serialize('xml', Note.objects.all())
    return HttpResponse(data, content_type="application/xml")

def json(request):
    data = serializers.serialize('json', Note.objects.all())
    return HttpResponse(data, content_type="application/json")

lab_3/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .forms import FriendForm
from lab_1.models import Friend

@login_required(login_url='/admin/login/')
def index(request):
    friend_list = Friend.objects.all()
    response = {'friend_list': friend_list}

    return render(request, 'lab3_index.html', response)

@login_required(login_url='/admin/login/')
def add_friend(request):
    form = FriendForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect('/lab-3')

    response = {'form': form}
    
    return render(request, 'lab3_form.html', response)

lab_4/views.py
from django.shortcuts import render, redirect
from .forms import NoteForm
from lab_2.models import Note

def index(request):
    note_list = Note.objects.all()
    response = {'note_list': note_list,
            }
    return render(request, 'lab4_index.html', response)

def add_note(request):
    form = NoteForm(request.POST or None)

    if request.method == "POST" and form.is_valid():
        form.save()
        return redirect('/lab-4/')

    response = {'form': form}
    
    return render(request, 'lab4_form.html', response)

def note_list(request):
    note_list = Note.objects.all()
    response = {'note_list': note_list,
            }
    return render(request, 'lab4_note_list.html', response)

lab_5/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.views.generic import View
from .forms import NoteForm
from lab_2.models import Note

def index(request):
    note_list = Note.objects.all()
    response = {'note_list': note_list,
            }
    return render(request, 'lab5_index.html', response)

def add_note(request):
    form = NoteForm(request.POST or None)

    if request.method == "POST" and form.is_valid():
        form.save()
        return redirect('/lab-5/')

    response = {'form': form}
    
    return render(request, 'lab5_form.html', response)

def note_list(request):
    note_list = Note.objects.all()
    response = {'note_list': note_list,
            }
    return render(request, 'lab5_note_list.html', response)

class EditNote(View):
    def get(self, request):
        id1 = request.GET.get('id', None)
        title1 = request.GET.get('title', None)
        note_from1 = request.GET.get('note_from', None)
        note_to1 = request.GET.get('note_to', None)
        message1 = request.GET.get('message', None)

        obj = Note.objects.get(id=id1)
        obj.title = title1
        obj.note_from = note_from1
        obj.note_to = note_to1
        obj.message = message1

        note = {
            'id':obj.id,
            'title':obj.title,
            'note_from':obj.note_from,
            'note_to':obj.note_to,
            'message':obj.message    
        }

        data = {
            'note': note
        }
        return JsonResponse(data)

class DeleteNote(View):
    def  get(self, request):
        id1 = request.GET.get('id', None)
        Note.objects.get(id=id1).delete()
        data = {
            'deleted': True
        }
        return JsonResponse(data)

lab_1/templates/friend_list_lab1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Friend List</title>
  </head>
  <body>
    <table cellspacing="10">
      <tr>
        <th>Name</th>
        <th>NPM</th>
        <th>DOB</th>
      </tr>
      <!-- Loop from Friend model -->
      {% if friend_list %}
        {% for friend in friend_list %}
          <tr>
	    <td>{{ friend.name }}</td>
	    <td>{{ friend.npm }}</td>
	    <td>{{ friend.DOB|date:'M d, Y' }}</td>
	  </tr>
	{% endfor %}
      {% endif %}
    </table>
  </body>
</html>

lab_1/templates/index_lab1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{{ name }}</title>
  </head>
  <body>
    <h1>Hello my name is {{ name }}</h1>
    <article>NPM : {{ npm }}</article>
    <article>I am {{ age }} years old</article>
  </body>
</html>

lab_2/templates/lab2.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Note List</title>
  </head>
  <body>
    <h1>Note List</h1>
    <table border="1" width="100%" cellspacing="0" cellpadding="10">
	<tr>
	  <th>Title</th>
	  <th>Sender</th>
	  <th>Receiver</th>
	  <th>Message</th>
	</tr>
        {% for note in note_list %}
	  <tr>
    	    <td>{{ note.title }}</td>
    	    <td>{{ note.note_from }}</td>
    	    <td>{{ note.note_to }}</td>
	    <td>{{ note.message|linebreaksbr }}</td>
	  </tr>
	{% endfor %}
    </table>
  </body>
</html>

lab_3/templates/lab3_form.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Add Friend</title>
  </head>
  <body>
    <div class="form">
    <form action="" method="POST">
        {% csrf_token %}
	<table cellpadding="5">
	    <tr><th colspan="2" style="font-size: 28px">Add Friend</th></tr>
	    {{ form.as_table }}
	    <tr><td colspan="2" style="text-align:center">
	        <input type="submit" value="Submit">
	    </td></tr>
	</table>
    </form>
    </div>
  </body>
</html> 

lab_3/templates/lab3_index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Friend List</title>
  </head>
  <body>
    <table cellspacing="10">
      <tr>
        <th>Name</th>
        <th>NPM</th>
        <th>DOB</th>
      </tr>
      <!-- Loop from Friend model -->
      {% if friend_list %}
        {% for friend in friend_list %}
          <tr>
            <td>{{ friend.name }}</td>
            <td>{{ friend.npm }}</td>
            <td>{{ friend.DOB|date:'M d, Y' }}</td>
          </tr>
        {% endfor %}
      {% endif %}
    </table>
  </body>
</html>

lab_4/templates/lab4_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8"/>
    <title>Add Note</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/bootstrap.css' %}">
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <a class="navbar-brand" href=".">Lab 4</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link text-white" href="/lab-4/">Table Note</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="/lab-4/note-list">Card Note</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="/lab-4/add-note">Add Note</a>
          </li>
        </ul>
      </div>
    </nav>

    <div class="jumbotron jumbotron-fluid">
      <div class="container">
        <h1 class="font-weight-bold">Add Note</h1>
      </div>
    </div>

    <div class="container-fluid">
      <div class="container bg-white shadow">
        <div class="form">
          <form action="" method="POST">
            {% csrf_token %}
            <div class="form-group row">
              <label for="id_title" class="col-sm-1 col-form-label">Title:</label>
              <div class="col-sm-4">
                <input type="text" name="title" class="form-control" maxlength="30" required id="id_title">
              </div>
            </div>
            <div class="form-group row">
              <label for="id_note_from" class="col-sm-1 col-form-label">From:</label>
              <div class="col-sm-4">
                <input type="text" name="note_from" class="form-control" maxlength="30" required id="id_note_from">
              </div>
            </div>
            <div class="form-group row">
              <label for="id_note_to" class="col-sm-1 col-form-label">To:</label>
              <div class="col-sm-4">
                <input type="text" name="note_to" class="form-control" maxlength="30" required id="id_note_to">
              </div>
            </div>
            <div class="form-group row">
              <label for="id_message" class="col-sm-1 col-form-label">Message:</label>
              <div class="col-sm-4">
                <textarea name="message" class="form-control" cols="40" rows="10" required id="id_message"></textarea>
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-1"></label>
              <div class="col-sm-4">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>

    <script src="{% static 'vendor/jquery/jquery.js' %}" type="text/javascript"></script>
    <script src="{% static 'vendor/popper/popper.js' %}" type="text/javascript"></script>
    <script src="{% static 'vendor/bootstrap/bootstrap.js' %}" type="text/javascript"></script>

  </body>
</html> 

lab_4/templates/lab4_index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8"/>
    <title>Table Note</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/bootstrap.css' %}">
  </head>

  <body>

  	<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
		  <a class="navbar-brand" href=".">Lab 4</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>

		  <div class="collapse navbar-collapse" id="navbarSupportedContent">
		    <ul class="navbar-nav mr-auto">
		      <li class="nav-item">
		        <a class="nav-link text-white" href="/lab-4/">Table Note</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link text-white" href="/lab-4/note-list">Card Note</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link text-white" href="/lab-4/add-note">Add Note</a>
		      </li>
		    </ul>
		  </div>
		</nav>

		<div class="jumbotron jumbotron-fluid">
      <div class="container">
        <h1 class="font-weight-bold">Table Note</h1>
      </div>
    </div>

    <div class="container-fluid">
      <div class="container bg-white shadow">
        <table class="table table-hover table-striped">
	  			<thead class="bg-primary text-white">
				    <tr>
				      <th scope="col">Title</th>
				      <th scope="col">Sender</th>
				      <th scope="col">Receiver</th>
				      <th scope="col">Message</th>
				    </tr>
				  </thead>
				        {% for note in note_list %}
					  <tr>
				    	    <td>{{ note.title }}</td>
				    	    <td>{{ note.note_from }}</td>
				    	    <td>{{ note.note_to }}</td>
					    <td>{{ note.message|linebreaksbr }}</td>
					  </tr>
					{% endfor %}
				</table>
      </div>
    </div>

  	<script src="{% static 'vendor/jquery/jquery.js' %}" type="text/javascript"></script>
  	<script src="{% static 'vendor/popper/popper.js' %}" type="text/javascript"></script>
    <script src="{% static 'vendor/bootstrap/bootstrap.js' %}" type="text/javascript"></script>

  </body>
</html>

lab_4/templates/lab4_note_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8"/>
    <title>Card Note</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/bootstrap.css' %}">
  </head>

  <body>

  	<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <a class="navbar-brand" href=".">Lab 4</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link text-white" href="/lab-4/">Table Note</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="/lab-4/note-list">Card Note</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" href="/lab-4/add-note">Add Note</a>
          </li>
        </ul>
      </div>
    </nav>

    <div class="jumbotron jumbotron-fluid">
      <div class="container">
        <h1 class="font-weight-bold">Card Note</h1>
      </div>
    </div>

    <div class="container-fluid">
      <div class="container bg-white shadow">
        <div class="card-columns">
          {% for note in note_list %}
          <div class="card border-primary mb-3">
            <div class="card-header text-white bg-primary">{{ note.title }}</div>
            <div class="card-body text-primary bg-light">
              <p class="card-text">From: {{ note.note_from }}</p>
              <p class="card-text">To: {{ note.note_to }}</p>
              <p class="card-text">{{ note.message|linebreaksbr }}</p>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>

    <script src="{% static 'vendor/jquery/jquery.js' %}" type="text/javascript"></script>
    <script src="{% static 'vendor/popper/popper.js' %}" type="text/javascript"></script>
    <script src="{% static 'vendor/bootstrap/bootstrap.js' %}" type="text/javascript"></script>

  </body>
</html>

lab_5/templates/lab5_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8"/>
    <title>Add Note</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <a class="navbar-brand" href=".">Lab 5</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link text-white" href="/lab-5/">Table Note</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="/lab-5/note-list">Card Note</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="/lab-5/add-note">Add Note</a>
          </li>
        </ul>
      </div>
    </nav>

    <div class="jumbotron jumbotron-fluid">
      <div class="container">
        <h1 class="font-weight-bold">Add Note</h1>
      </div>
    </div>

    <div class="container-fluid">
      <div class="container bg-white shadow">
        <div class="form">
          <form action="" method="POST">
            {% csrf_token %}
            <div class="form-group row">
              <label for="id_title" class="col-sm-1 col-form-label">Title:</label>
              <div class="col-sm-4">
                <input type="text" name="title" class="form-control" maxlength="30" required id="id_title">
              </div>
            </div>
            <div class="form-group row">
              <label for="id_note_from" class="col-sm-1 col-form-label">From:</label>
              <div class="col-sm-4">
                <input type="text" name="note_from" class="form-control" maxlength="30" required id="id_note_from">
              </div>
            </div>
            <div class="form-group row">
              <label for="id_note_to" class="col-sm-1 col-form-label">To:</label>
              <div class="col-sm-4">
                <input type="text" name="note_to" class="form-control" maxlength="30" required id="id_note_to">
              </div>
            </div>
            <div class="form-group row">
              <label for="id_message" class="col-sm-1 col-form-label">Message:</label>
              <div class="col-sm-4">
                <textarea name="message" class="form-control" cols="40" rows="10" required id="id_message"></textarea>
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-1"></label>
              <div class="col-sm-4">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js" integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

  </body>
</html> 

lab_5/templates/lab5_index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8"/>
    <title>Table Note</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  </head>

  <body>

  	<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
		  <a class="navbar-brand" href=".">Lab 5</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>

		  <div class="collapse navbar-collapse" id="navbarSupportedContent">
		    <ul class="navbar-nav mr-auto">
		      <li class="nav-item">
		        <a class="nav-link text-white" href="/lab-5/">Table Note</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link text-white" href="/lab-5/note-list">Card Note</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link text-white" href="/lab-5/add-note">Add Note</a>
		      </li>
		    </ul>
		  </div>
		</nav>

		<div class="jumbotron jumbotron-fluid">
      <div class="container">
        <h1 class="font-weight-bold">Table Note</h1>
      </div>
    </div>

    <div class="modal fade" id="modal-note" tabindex="-1" role="dialog" aria-hidden="true">
			<div class="modal-dialog modal-dialog-centered" role="document">
				<div class="modal-content">
					<div class="modal-header"></div>
					<div class="modal-body"></div>
					<div class="modal-footer">
					  <button id="button-close"class='btn btn-secondary' data-dismiss='modal'>Close</button>
				  </div>
			  </div>
			</div>
		</div>

		<div class="modal fade" id="modal-edit" tabindex="-1" role="dialog" aria-hidden="true">
	    <div class="modal-dialog" role="document">
	      <div class="modal-content">
	        <div class="modal-header">
	          <h3><b>Edit Note</b></h3>
	        </div>
	        <form action="">
	        <div id="editButton" class="modal-body">
	          <label for="id_title">Title</label>
	          <input type="text" name="title" class="form-control" maxlength="30" required id="id_title">
	          <label for="id_note_from">From</label>
            <input type="text" name="note_from" class="form-control" maxlength="30" required id="id_note_from">
	          <label for="id_note_to">To</label>
	          <input type="text" name="note_to" class="form-control" maxlength="30" required id="id_note_to">
	          <label for="id_message">Message</label>
	          <textarea name="message" class="form-control" cols="40" rows="10" required id="id_message"></textarea>
	        </div>
	        <div class="modal-footer">
	            <button type="submit" class="btn btn-primary">Save changes</button>
	            <button class="btn btn-secondary" data-dismiss="modal">Close</button>
	        </div>
	        </form>
	      </div>
	    </div>
	  </div>


    <div class="container-fluid">
      <div class="container bg-white shadow">
        <table class="table table-hover table-striped" id="table-note">
	  			<thead class="bg-primary text-white">
				    <tr>
				      <th scope="col">Title</th>
				      <th scope="col">Sender</th>
				      <th scope="col">Receiver</th>
				      <th scope="col">Message</th>
				      <th scope="col">Actions</th>
				    </tr>
				  </thead>

				  {% for note in note_list %}
					  <tr id="{{ note.id }}">
				    	<td class="title">{{ note.title }}</td>
				    	<td class="from">{{ note.note_from }}</td>
				    	<td class="to">{{ note.note_to }}</td>
					    <td class="message">{{ note.message|linebreaksbr }}</td>
					    <td>
					    		<button data-selector="{{ note.id }}" class="btn btn-secondary btn-sm view-note" data-toggle="modal" data-target="#modal-note">View</button>
							    <button data-selector="{{ note.id }}" class="btn btn-secondary btn-sm edit-note" data-toggle="modal"data-target="#modal-edit">Edit</button>
							    <button data-selector="{{ note.id }}" class="btn btn-secondary btn-sm del-note" data-toggle="modal"data-target="#modal-note">Delete</button>
					    </td>
					  </tr>
					{% endfor %}
				</table>
      </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js" integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
		<script src="{% static 'js/scripts.js' %}" type="text/javascript"></script>

  </body>
</html>